import type { DashboardSnapshot } from "@learn-it/shared";

export const sampleDashboard: DashboardSnapshot = {
  understandingScore: 67,
  conceptsMasteredThisWeek: 4,
  retentionRate: 82,
  implementationCompletion: 38,
  concepts: [
    {
      id: "paper",
      label: "Attention Is All You Need",
      depth: 2,
      status: "developing",
      retrievalHealth: 74,
      nextReviewAt: "Today",
    },
    {
      id: "matmul",
      label: "Matrix multiplication",
      depth: 3,
      status: "strong",
      retrievalHealth: 88,
      nextReviewAt: "Jun 21",
    },
    {
      id: "dot",
      label: "Dot products",
      depth: 2,
      status: "developing",
      retrievalHealth: 71,
      nextReviewAt: "Tomorrow",
    },
    {
      id: "softmax",
      label: "Softmax",
      depth: 1,
      status: "weak",
      retrievalHealth: 46,
      nextReviewAt: "Today",
    },
    {
      id: "embeddings",
      label: "Embeddings",
      depth: 2,
      status: "developing",
      retrievalHealth: 69,
      nextReviewAt: "Jun 22",
    },
    {
      id: "info",
      label: "Information theory",
      depth: 0,
      status: "missing",
      retrievalHealth: 18,
      nextReviewAt: "Today",
    },
  ],
  edges: [
    { source: "matmul", target: "paper", relation: "prerequisite", confidence: 0.94 },
    { source: "dot", target: "paper", relation: "prerequisite", confidence: 0.91 },
    { source: "softmax", target: "paper", relation: "prerequisite", confidence: 0.89 },
    { source: "embeddings", target: "paper", relation: "supports", confidence: 0.82 },
    { source: "info", target: "paper", relation: "supports", confidence: 0.67 },
  ],
  path: [
    {
      id: "diagnose-softmax",
      conceptId: "softmax",
      stage: "diagnose",
      title: "Diagnose softmax intuition",
      learnerAction: "Predict how logits change probabilities before seeing the formula.",
      estimatedMinutes: 8,
    },
    {
      id: "apply-dot-products",
      conceptId: "dot",
      stage: "apply",
      title: "Apply dot products to attention scores",
      learnerAction: "Compute three token-to-token scores by hand.",
      estimatedMinutes: 15,
    },
    {
      id: "explain-attention",
      conceptId: "paper",
      stage: "explain",
      title: "Teach back scaled dot-product attention",
      learnerAction: "Explain the operation without using the word magic.",
      estimatedMinutes: 12,
    },
  ],
};
